added server
ASeegull/SmartFridge pull request #2
Opened 2017-11-16 19:41 UTC by AndriiPryslupskyi

Created server and app structure.
Created postgres database methods and realized mongodb methods (used mongo atlas).

2017-11-17 13:15 UTC, 8tomat8 requested changes

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +	yamlFile, err := ioutil.ReadFile("../SmartFridge/mongoConfig.yaml")
Move path to const or add flag with default value.

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +type FoodInfo struct {
Please move models to corresponding package or file. Try not to store everything in one file.

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +	mongoConfig.getConf()
It would be handy to have one package that will manage all config files. Also it will allow to avoid using `init()` func

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +	dialInfo, _ := mgo.ParseURL(mongoURI)
Do not skip errors!

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +	var mongoURI = mongoConfig.MongoURI
Why do you need this extra variable?

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +		log.WithFields(log.Fields{"error: ": err}).Info("Cannot create session to mongoDB")
Please return errors to process it in caller.

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +	session, err := getSession()
Why are you creating new session on each call? You can initialize connection pool one time on start and then use it.

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +		return []FoodInfo{}
Please return error to process it on caller.

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +		if err := c.Find(bson.M{"token": value}).One(&agent); err == nil {
Where is check `if err!=nil`? You have to return it or at least log it.

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/postgres.go
> +	days := 10
Move this variable to constant

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/postgres.go
> +	return []string{}, nil
Zero type for slice is `nil` so you can avoid creation of new slice.

2017-11-17 13:15 UTC, 8tomat8 commented on server/database/mongo.go
> +		return []FoodInfo{}
Zero type for slice is `nil` so you can avoid creation of new slice.

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +	yamlFile, err := ioutil.ReadFile("../SmartFridge/fridgeServerConfig.yaml")
Move path to const or add flag with default value.

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +		log.WithFields(log.Fields{"error: ": err}).Info("Cannot read ../SmartFridge/fridgeServerConfig.yaml")
Please return errors to process them from caller

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +		log.WithFields(log.Fields{"error: ": err}).Info("Unmarshal yamlFile error")
When you have only one field - you can use `log.WithField`

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +	ReadBufferSize:  1024,
Will it be enough? Maybe it would be better to have this values in config file?

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +	go wsListener(conn)
You have to handle all goroutines properly. Please use `sync.WaitGroup` to track number of running goroutines. Otherwise you will get goroutine leak

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +	body, err := ioutil.ReadAll(r.Body)
You have to close Body after read

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +	clientID := string(body[1 : len(body)-2])
What the magic? Please use `json` or store data in headers.

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +}
Please move handlers to separate package or file

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +	router.HandleFunc("/client/allRecipes", getRecipes).Methods("GET")
You can create nested handlers to avoid copying `/client` on each endpoint

2017-11-17 13:15 UTC, 8tomat8 commented on server/fridgeServer.go
> +	serverConfig.getConf()
The same about configuration

2017-11-17 17:38 UTC, ASeegull requested changes

2017-11-17 17:38 UTC, ASeegull commented on server/fridgeServer.go
> +	yamlFile, err := ioutil.ReadFile("../SmartFridge/fridgeServerConfig.yaml")
The path is relative to directory, where the process is initialized (/server in this case). Your path to config file should look like "../../fridgeServerConfig.yaml"

2017-11-17 20:39 UTC, ASeegull approved these changes

2017-11-18 09:15 UTC, 8tomat8 requested changes

2017-11-18 09:15 UTC, 8tomat8 commented on cmd/server/main.go
> +	fmt.Printf("Server started with address %s:%s\n", host, port)
Please do not use `fmt` for logging.

2017-11-18 09:15 UTC, 8tomat8 commented on server/config/config.go
> +	log "github.com/sirupsen/logrus"
Please install new packages using glide and don't forget to add `glide.yaml` file changes after that.
https://github.com/Masterminds/glide

2017-11-18 09:15 UTC, 8tomat8 commented on server/config/config.go
> +	yamlFile, err := ioutil.ReadFile(mongoConfigPath)
You will parse config file each time when you need any value? Maybe it would be better to do it one time on app start

2017-11-18 09:15 UTC, 8tomat8 commented on server/config/config.go
> +	return config
If error ocurred, will you be able to manage it on caller?

2017-11-18 09:15 UTC, 8tomat8 commented on server/config/config.go
> +	yamlFile, err := ioutil.ReadFile(serverConfigPath)
You will parse config file each time when you need any value? Maybe it would be better to do it one time on app start

2017-11-18 09:15 UTC, 8tomat8 commented on server/config/config.go
> +func GetServerConfig() *ServerConfig {
Please merge all configs to one.

2017-11-18 09:15 UTC, 8tomat8 commented on server/database/mongo.go
> +	dialInfo, _ := mgo.ParseURL(mongoConfig.URI)
Please don't skip errors checks and return them to caller.

2017-11-18 09:15 UTC, 8tomat8 commented on server/database/mongo.go
> +		log.Error(err)
Why you not returning errors?

2017-11-18 09:15 UTC, 8tomat8 commented on server/database/mongo.go
> +			log.Error(err)
And again errors!!!!!111111111111

2017-11-18 09:15 UTC, 8tomat8 commented on server/handlers.go
> +var wg sync.WaitGroup
Wait group have to be connected or to be available from `main()` to handle graceful shutdown.

2017-11-18 09:15 UTC, 8tomat8 commented on server/handlers.go
> +	json.NewEncoder(w).Encode(tokenExample)
Where is error handling? Are you immortal?

2017-11-18 09:15 UTC, 8tomat8 commented on server/handlers.go
> +	for {
Do not use not controlled infinitive loops! You would burn out your CPU.
Add some blocking operation not to fun `for` all the time.

2017-11-18 09:15 UTC, 8tomat8 commented on server/handlers.go
> +	json.NewEncoder(w).Encode(foods)
ERRORS!!!

2017-11-18 15:22 UTC, 8tomat8 requested changes

2017-11-18 15:22 UTC, 8tomat8 commented on server/fridgeServer.go
> +	wg = waitGroup
Try to avoid global states.
It is not obvious for client that he has to Set this wg before usage.
It would be better to create struct with this wait group and propagate it further.

2017-11-18 15:22 UTC, 8tomat8 commented on server/database/mongo.go
> +		log.Error(err)
Please return errors and handle them on caller.

2017-11-18 15:22 UTC, 8tomat8 commented on server/handlers.go
> +		time.Sleep(time.Second * serverConfig.WebsocketSleep)
Bad approach =)
`conn.ReadMessage()` and `conn.ReadJSON()` are already blocking

2017-11-18 15:22 UTC, 8tomat8 commented on server/handlers.go
> +		log.Print(err)
Return error.

2017-11-18 15:22 UTC, 8tomat8 commented on server/fridgeServer.go
> +	database.InitiateMongoDB(mongoDBConfig)
Why are you initialize mongo in `ReadConfig` ? Please move this logic to database package

2017-12-01 10:37 UTC, anastasiia-skliar approved these changes

2017-12-05 11:50 UTC, closed without merging