Added product CRUD functions and handlers
ASeegull/SmartFridge pull request #20
Opened 2017-12-17 01:52 UTC by oleksandrkravchuk87

2017-12-17 18:12 UTC, AndriiPryslupskyi requested changes

2017-12-17 18:12 UTC, AndriiPryslupskyi commented on server/database/postgres.go
> +	return err
You can return db.Create()

2017-12-17 18:12 UTC, AndriiPryslupskyi commented on server/database/postgres.go
> +	return err
You can return db.Save()

2017-12-17 18:12 UTC, AndriiPryslupskyi commented on server/database/postgres.go
> +	if shelfLife != 0 {
Can shelfLife be negative?)

2017-12-17 18:12 UTC, AndriiPryslupskyi commented on server/database/postgres.go
> +	return err
Again return db.Where()

2017-12-17 18:12 UTC, AndriiPryslupskyi commented on server/fridgeServer.go
> +	sub.HandleFunc("/product/getByID/{name}", checkSession(getProductByName)).Methods(GET)
Maybe getByName in path?

2017-12-18 10:20 UTC, Nastya-Kruglikova commented on server/fridgeServer.go
> +	sub.HandleFunc("/product/getByID/{name}", checkSession(getProductByName)).Methods(GET)
https://geemus.gitbooks.io/http-api-design/content/en/requests/resource-names.html

Use /products better

2017-12-18 10:21 UTC, Nastya-Kruglikova commented on server/handler.go
> +	name := vars["name"]
Maybe 
name := mux.Vars(r)["name"]

As variable vars is used only once

2017-12-19 14:09 UTC, AndriiPryslupskyi approved these changes

2017-12-20 15:42 UTC, merged